services:
  frontend:
    container_name: vite-frontend
    build:
      context: .
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    command: ["npm", "run", "dev"]
    restart: always

  backend:
    container_name: fastapi-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
